title: Maths in the Wild
theme: minima
markdown: kramdown

# Navigation menu items
header_pages:
  - 01_Predator_Prey/index.md
  - 02_NeuroAI/index.md
  - 03_Multisensory/index.md
  - 04_DecisionMaking/index.md
  - 05_EigenFaces/index.md
  - 99_Misc/index.md
